### ISSUE TITLE
Block times more granular when 1 sec

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [blockchain-etl/eos-etl#8]
look at this 2 blocks - they are produced in the same exact second:
https://eosq.app/block/0179873f0684f095e7cea6b679c9eb94e035fa00f2d98dc65804ba16cca58398
https://eosq.app/block/0179874001656e469f409aed1b7e99f7958cfb61778941e022b9e4729692a3da

When querying block number by date it will result in 

`timestamp < Nov 2, 2018 6:59:59 AM +07`

so first block is returned while second is not.

have to rewrite logic of guessing block numbers by date.

**Comment by Vasiliy-Bondarenko** [comment]
This issues is related to all ETLs resulting in some blocks missing from exported data.
It is possible to have 2 or more blocks produced at the same second even on POW chains. It will be rare case, but still possible. So worth fixing all ETLs.

**Comment by medvedev1088** [comment]
Thanks for reporting this! Please try [graph_operations.py](https://github.com/blockchain-etl/bitcoin-etl/blob/master/blockchainetl/service/graph_operations.py) from bitcoin-etl. As we discussed before, in Ethereum the timestamps are strictly monotonic, unlike Bitcoin where blocks can have the same timestamp and even the timestamp of next blocks can be earlier than a timestamp of a previous block. You will need to make the `MAX_ITERATIONS_FIND_POINT_AROUND` a parameter so that for EOS you could pass 5, for example. For Bitcoin it's currently 119 which means that for any given block number X there can be another block number in the range (X, X+119) that has the same or earlier timestamp.

I was going to factor out the blockchainetl package to a separate lib and include it in both ethereum-etl and bitcoin-etl, but I didn't have time for this.

You may also need to update graph_operations.py to make sure it supports timestamps with milliseconds. 

`prefetch_left = min(20 if move_left else 0, next_point_x)` - 20 here is batch size. Since EOS doesn't support batching it should be 0 for EOS. Then this value should be passed in the __init__ method of GraphOperations.

Note that in the Airflow DAG there is a simple check at the end to verify there are no missing or duplicate blocks https://github.com/blockchain-etl/bitcoin-etl-airflow/blob/master/dags/resources/stages/verify/sqls/blocks_count.sql. At this point presumably there are no missing or duplicate blocks in Ethereum and Bitcoin datasets.
